FROM node:20-alpine AS builder

WORKDIR /app

COPY package*.json turbo.json ./
COPY libs ./libs
COPY apps/api ./apps/api

RUN npm install
RUN npm run build

FROM node:20-alpine AS runner

WORKDIR /app

ENV NODE_ENV=production

COPY --from=builder /app/package*.json ./
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/apps/api/dist ./apps/api/dist
COPY --from=builder /app/libs ./libs

EXPOSE 3000

CMD ["node", "apps/api/dist/main"]
